### PR TITLE
Docker is goat

### PR DESCRIPTION
**Pull request by SheepIsGoat**
## Description
Two major changes
1.  Dockerfile and docker-compose rework. 
2. Splitting the gigantic app.py into a package.

Fixes # (issue)
Docker changes includes mounting local volumes for persistent model storage, and overcomes some of the issues with bindings_zoo. Also lets containers support cuda and use miniconda on the container in multistage builds, to help make the build cache must faster.
`GPU=nvidia docker-compose -f docker/nvidia/docker-compose.yml build`
`GPU=nvidia docker-compose -f docker/nvidia/docker-compose.yml up`
app.py was very difficult to read as a 2300+ line monofile. Splitting it into a directory tree could make it much easier to maintain and organize over time. For example, I found one function that was implemented twice in the same file. Note, my python linter is having issues so it may have missed some imports.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:
Please put an `x` in the boxes that apply. You can also fill these out after creating the PR.

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested this code locally, and it is working as intended
- [ ] I have updated the documentation accordingly

## Screenshots
If applicable, add screenshots to help explain your changes.

### CODE REVIEW

**Review by ParisNeo — APPROVED** [review]
Legit

**Comment by SheepIsGoat** [comment]
I moved the Dockerfiles so the build context is failing, let me update the .gitHub/workflows yaml to use the right path

**Comment by ParisNeo** [comment]
image
Still something is wrong.

**Comment by ParisNeo** [comment]
the docker is still failing on actions.

**Comment by LTangaF** [comment]
May want to rebase this and then address the same issue that I commented on in https://github.com/ParisNeo/lollms-webui/issues/435#issuecomment-1847788252 . static files have been moved around since this branch was created.

**Pull request closed without merging**
